[workspace]
resolver = "3"
members = ["libattest", "nvidia-attest", "reticle", "snp-attest", "tdx-attest", "attestation-server", "azure-attest"]

[patch.crates-io]
sev = { git = "https://github.com/BRA1L0R/sev", branch = "prem" }

[workspace.dependencies]
anyhow = "1.0.100"
getrandom = "=0.2.16"
hex = "0.4.3"
libattest = { path = "libattest" }
reqwest = "0.13.2"
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = "1.49.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
x509-cert = "0.3.0-rc.4"
zerocopy = "0.8.48"
base64 = "0.22.1"
web-time = "1.1"
rsa = "0.10.0-rc.18"
sev = { version = "7.1.0", default-features = false }
