SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

SET(CMAKE_C_COMPILER /usr/bin/x86_64-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/x86_64-linux-gnu-g++)

if(DEFINED ENV{SYSROOT})
    set(SYSROOT $ENV{SYSROOT})
else()
    set(SYSROOT /x86_64-sysroot)
endif()

SET(CMAKE_FIND_ROOT_PATH ${SYSROOT})

# Tell the cross-compiler to use the sysroot
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L${SYSROOT}/lib")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -L${SYSROOT}/lib")
if(NOT DEFINED CMAKE_FIND_ROOT_PATH_MODE_PROGRAM)
    SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
endif()
if(NOT DEFINED CMAKE_FIND_ROOT_PATH_MODE_LIBRARY)
    SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
endif()
if(NOT DEFINED CMAKE_FIND_ROOT_PATH_MODE_INCLUDE)
    SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
endif()
if(NOT DEFINED CMAKE_FIND_ROOT_PATH_MODE_PACKAGE)
    SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()

SET(Rust_CARGO_TARGET "x86_64-unknown-linux-gnu")
