SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

SET(CMAKE_C_COMPILER /usr/bin/x86_64-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/x86_64-linux-gnu-g++)

SET(CMAKE_SYSROOT /x86_64-sysroot)

SET(CMAKE_FIND_ROOT_PATH "/x86_64-sysroot")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

SET(Rust_CARGO_TARGET "x86_64-unknown-linux-gnu")