[package]
name = "tdx-attest"
version = "0.1.0"
edition = "2024"

[dependencies]
# dcap-qvl = "0.3"
# tdx-quote = "0.0.5"
libattest.workspace = true
thiserror.workspace = true
zerocopy = { workspace = true, features = ["derive"] }
x509-cert = { workspace = true, features = ["pem"] }
spki = "0.8.0-rc.4"
der = { version = "0.8.0-rc.10", features = ["derive", "oid", "std"] }
# x509-verify = { version = "0.4.8", features = ["ed25519", "p256", "sha2", "x509"], default-features = false }
signature = "3.0"
sec1 = "0.7.3"
reqwest = { workspace = true, features = ["json", "query"] }
chrono = { version = "0.4.44", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
anyhow.workspace = true
hex = { workspace = true, features = ["serde"] }
urlencoding = "2.1.3"
const-oid = "0.10.2"
sha2 = "0.10.9"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-time.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
