[package]
name = "reticle"
version = "0.5.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = "1.11.0"
nvidia-attest = { path = "../nvidia-attest" }
reqwest.workspace = true
snp-attest = { path = "../snp-attest" }
tdx-attest = { path = "../tdx-attest" }
azure-attest = { path = "../azure-attest" }
attestation-protocol = { path = "../attestation-protocol" }
thiserror.workspace = true
wasm-bindgen.workspace = true
serde-wasm-bindgen = "0.6"
wasm-bindgen-futures.workspace = true
console_error_panic_hook = "0.1"
libattest.workspace = true
serde = { workspace = true, features = ["derive"] }
hex.workspace = true
futures = "0.3.32"
web-sys = { version = "0.3.98", features = ["Request", "RequestInit"] }
async-once-cell = "0.5.4"
async-trait = "0.1.89"
anyhow = { workspace = true, optional = true }
clap = { version = "4.6.4", features = ["derive", "env"], optional = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"], optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[features]
debug = []
cvmcli = ["dep:anyhow", "dep:clap", "dep:tokio"]

[[bin]]
name = "cvmcli"
path = "src/bin/cvmcli.rs"
required-features = ["cvmcli"]

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
split-linked-modules = true
