[package]
name = "reticle"
version = "0.5.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = "1.11.0"
nvidia-attest = { path = "../nvidia-attest" }
reqwest.workspace = true
snp-attest = { path = "../snp-attest" }
tdx-attest = { path = "../tdx-attest" }
azure-attest = { path = "../azure-attest" }
thiserror.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
console_error_panic_hook = "0.1"
libattest.workspace = true
serde = { workspace = true, features = ["derive"] }
hex.workspace = true
futures = "0.3.32"
web-sys = { version = "0.3.98", features = ["Request", "RequestInit"] }
async-once-cell = "0.5.4"
async-trait = "0.1.89"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[features]
debug = []

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
split-linked-modules = true
