[package]
name = "azure-attest"
version = "0.1.0"
edition = "2024"

[features]
cli = ["dep:tss-esapi", "dep:anyhow"]

[dependencies]
tpm2-protocol = "0.16.0"
snp-attest = { path = "../snp-attest" }
tdx-attest = { path = "../tdx-attest" }
x509-cert = "0.3.0-rc.4"
rsa = { version = "0.10.0-rc.18", features = ["serde"] }
libattest = { path = "../libattest" }
jsonwebtoken = { version = "10.3.0", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.11.0"
serde_json = "1.0.149"
thiserror = "2.0.17"
zerocopy = { version = "0.8.48", features = ["derive"] }

tss-esapi = { version = "7.7.0", optional = true }
anyhow = { version = "*", optional = true }

[dev-dependencies]

[[bin]]
name = "generate-report"
path = "src/bin/generate.rs"
required-features = ["cli"]
