[package]
name = "azure-attest"
version = "0.1.0"
edition = "2024"

[features]
host = ["dep:tss-esapi", "dep:anyhow"]
cli = ["dep:tss-esapi", "dep:anyhow"]

[dependencies]
tpm2-protocol = "0.16.0"
snp-attest = { path = "../snp-attest" }
tdx-attest = { path = "../tdx-attest" }
x509-cert.workspace = true
rsa = { version = "0.10.0-rc.18", features = ["serde"] }
libattest.workspace = true
jsonwebtoken = { version = "10.3.0", default-features = false }
serde = { workspace = true, features = ["derive"] }
sha2 = "0.11.0"
serde_json.workspace = true
thiserror.workspace = true
zerocopy = { workspace = true, features = ["derive"] }

tss-esapi = { version = "7.7.0", optional = true }
anyhow = { workspace = true, optional = true }
base64 = "0.22.1"
hex = { workspace = true, features = ["serde"] }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[[bin]]
name = "generate-report"
path = "src/bin/generate.rs"
required-features = ["cli"]
